web:
  build: .
  environment:
   - DEBUG=False
  env_file:
   - ev.env
  volumes: 
   - ./src:/docker/src/
  ports: 
   - "8888:80"
  #- "8080:8080"
  # external_links: 
  #  - db
  command: bash -c "cd /docker/src/front/ && cnpm i && npm run build && python /docker/src/updatedb.py &&  supervisord -n"
  # command: bash -c "python /docker/src/updatedb.py &&  supervisord -n"