web:
  build: .
  environment:
   - DEBUG=True
   - DB_HOST=192.168.0.88
   - DB_PORT=32768
   - DB_NAME=lol
   - DB_PASSWORD=letmegoletmego
  volumes: 
   - ./src:/docker/src/
  ports: 
   - "80:80"
  # external_links: 
  #  - db
  command: bash -c "python /docker/src/updatedb.py &&  supervisord -n"