web:
  build: .
  environment:
   - DEBUG=True
   - DB_HOST=192.168.0.88
   - DB_PORT=32768
   - DB_NAME=pylinter
   - DB_PASSWORD=letmegoletmego
   - JENKINS_URL=http:/192.168.0.88:8080
   - JENKINS_USER=admin
   - JENKINS_TOKEN=049a35461892831cb3d0a79849ae8d55
  volumes: 
   - ./src:/docker/src/
  ports: 
   - "80:80"
  #- "8080:8080"
  # external_links: 
  #  - db
  command: bash -c "cd /docker/src/front/ && cnpm i && npm run build && python /docker/src/updatedb.py &&  supervisord -n"
  # command: bash -c "python /docker/src/updatedb.py &&  supervisord -n"