web:
  build: .
  environment:
   - DEBUG=True
   - DB_HOST=192.168.0.88
   - DB_PORT=32768
   - DB_NAME=lol
   - DB_PASSWORD=letmegoletmego
   - JENKINS_URL=http://192.168.0.88:32770/
   - JENKINS_USER=admin
   - JENKINS_TOKEN=82cb3f09bf21aaf77d7a2e799afe106f
  volumes: 
   - ./src:/docker/src/
  ports: 
   - "80:80"
  # external_links: 
  #  - db
  command: bash -c "python /docker/src/updatedb.py &&  supervisord -n"