web:
  build: .
  environment:
   - DEBUG=True
   - DB_NAME=lol
   - DB_PASSWORD=asheashe
  volumes: 
   - ./src:/docker/src/
  ports: 
   - "80:80"
  external_links: 
   - db
  command: bash -c "python /docker/src/updatedb.py &&  supervisord -n"